"""
Django settings for lapaznoesblanca project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!h+dc5+jm+3hiw-kvwd4tjsdhp^ax612pjhzgcm#lth2%a#ahv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🔒 SEGURIDAD: Agregamos tus dominios propios autorizados
ALLOWED_HOSTS = [
    'lapaznoesblanca.onrender.com', 
    'lapaznoesblanca.org',
    'www.lapaznoesblanca.org',
    'localhost', 
    '127.0.0.1'
]

# Application definition
INSTALLED_APPS = [
    "cloudinary_storage",
    "cloudinary",
    "django.contrib.staticfiles",    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "mapas", # Tu aplicación de mapas temporales y territoriales
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lapaznoesblanca.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lapaznoesblanca.wsgi.application"

# Database
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default="postgresql://postgres.lihwpavfekyygfapfrov:Tiberio2007$@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
    )
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "es-co"  # Cambiado a español de Colombia para tu comodidad
TIME_ZONE = "America/Bogota" # Ajustado a tu zona horaria local
USE_I18N = True
USE_TZ = True

# Configuración para archivos multimedia en la nube (Cloudinary)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'lihwpavfekyygfapfrov',
    'API_KEY': '172537597882996',
    'API_SECRET': 'VKvfgB8-DXMDezPmr0uYDU0rLcw'
}



# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Forzar a Django a usar Cloudinary para los archivos que subes
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'