"""
Django settings for lapaznoesblanca project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!h+dc5+jm+3hiw-kvwd4tjsdhp^ax612pjhzgcm#lth2%a#ahv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🔒 SEGURIDAD: Agregamos tus dominios propios autorizados
ALLOWED_HOSTS = [
    'lapaznoesblanca.onrender.com', 
    'lapaznoesblanca.org',
    'www.lapaznoesblanca.org',
    'localhost', 
    '127.0.0.1',
    'fundacion-pocoapoco.onrender.com'
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "cloudinary_storage",
    "django.contrib.staticfiles", 
    "cloudinary",
    "mapas", # Tu aplicación de mapas temporales y territoriales
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lapaznoesblanca.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lapaznoesblanca.wsgi.application"

# Database
import dj_database_url

# Base de datos conectada a Supabase
DATABASES = {
    'default': dj_database_url.config(
        default="postgresql://postgres.lihwpavfekyygfapfrov:Tiberio2007$@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "es-co"  # Cambiado a español de Colombia para tu comodidad
TIME_ZONE = "America/Bogota" # Ajustado a tu zona horaria local
USE_I18N = True
USE_TZ = True

# ☁️ Credenciales de Cloudinary CORREGIDAS (Sintaxis limpia)
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": "xhvjpkzs",
    "API_KEY": "172537597882996",
    "API_SECRET": "VKvfgB8-DXMDezPmr0uYDU0rLcw"
}

# Archivos Estáticos
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# 📂 Configuración moderna de almacenamiento para Django (Fuerza el uso de Cloudinary)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ... (al final de tu archivo settings.py)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')