# Generated by Django 6.0.6 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MapaSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(max_length=100, verbose_name="Municipio"),
                ),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("Atlantico", "Atlántico"),
                            ("Boyaca", "Boyacá"),
                            ("Cundinamarca", "Cundinamarca"),
                            ("Amazonas", "Amazonas"),
                            ("Antioquia", "Antioquia"),
                            ("Valle del Cauca", "Valle del Cauca"),
                        ],
                        max_length=50,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                        ],
                        default="2017",
                        max_length=4,
                        verbose_name="Año del Mapa",
                    ),
                ),
                (
                    "imagen_mapa",
                    models.ImageField(
                        upload_to="mapas_jpg/", verbose_name="Imagen del Mapa (JPG)"
                    ),
                ),
                (
                    "contexto_historico",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Análisis de Contexto / Memoria",
                    ),
                ),
                (
                    "coautores",
                    models.CharField(
                        default="Ivan Carroll y [Nombre del Colega]",
                        max_length=200,
                        verbose_name="Créditos de Autoría",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mapa de Líderes Sociales",
                "verbose_name_plural": "Mapas de Líderes Sociales",
                "ordering": ["-ano", "departamento", "municipio"],
            },
        ),
    ]
