# Generated by Django 6.0.6 on 2026-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapasocial",
            name="departamento",
            field=models.CharField(
                choices=[
                    ("Amazonas", "Amazonas"),
                    ("Antioquia", "Antioquia"),
                    ("Arauca", "Arauca"),
                    ("Atlantico", "Atlántico"),
                    ("Bogota", "Bogotá, D.C."),
                    ("Bolivar", "Bolívar"),
                    ("Boyaca", "Boyacá"),
                    ("Caldas", "Caldas"),
                    ("Caqueta", "Caquetá"),
                    ("Casanare", "Casanare"),
                    ("Cauca", "Cauca"),
                    ("Cesar", "Cesar"),
                    ("Choco", "Chocó"),
                    ("Cordoba", "Córdoba"),
                    ("Cundinamarca", "Cundinamarca"),
                    ("Guainia", "Guainía"),
                    ("Guaviare", "Guaviare"),
                    ("Huila", "Huila"),
                    ("La Guajira", "La Guajira"),
                    ("Magdalena", "Magdalena"),
                    ("Meta", "Meta"),
                    ("Narino", "Nariño"),
                    ("Norte de Santander", "Norte de Santander"),
                    ("Putumayo", "Putumayo"),
                    ("Quindio", "Quindío"),
                    ("Risaralda", "Risaralda"),
                    ("San Andres", "San Andrés y Providencia"),
                    ("Santander", "Santander"),
                    ("Sucre", "Sucre"),
                    ("Tolima", "Tolima"),
                    ("Valle del Cauca", "Valle del Cauca"),
                    ("Vaupes", "Vaupés"),
                    ("Vichada", "Vichada"),
                ],
                max_length=50,
                verbose_name="Departamento",
            ),
        ),
    ]
