# Generated by Django 6.0.6 on 2026-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0002_alter_mapasocial_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapasocial",
            name="coautores",
            field=models.CharField(
                default="Ivan CARROLL-JANER y Bognan Kadidja SEREME",
                max_length=200,
                verbose_name="Créditos de Autoría",
            ),
        ),
    ]
